services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
  redis:
    image: docker.io/bitnami/redis:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/bitnami/redis/data
  test-db:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: memqdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
volumes:
  pgdata:
  redis_data:
    driver: local

